{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-multi-llm-ai-gateway
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-llm-ai-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
